#!/usr/bin/env php
<?php

use Johmanx10\Transaction\Exception\FailedRollbackException;
use Johmanx10\Transaction\Formatter\FailedRollbackFormatter;
use Johmanx10\Transaction\Operation;
use Johmanx10\Transaction\Transaction;

require_once __DIR__ . '/../vendor/autoload.php';

$transaction = new Transaction(
    new Operation(
        function () {
            // Nothing to do.
        },
        null,
        'Operation Foo'
    ),
    new Operation(
        function () {
            // Nothing to do.
        },
        function () {
            throw new RuntimeException('Could not rollback Bar.');
        },
        'Operation Bar'
    ),
    new Operation(
        function () {
            // Nothing to do.
        },
        null,
        'Operation Baz'
    ),
    new Operation(
        function () {
            throw new RuntimeException('Failed operation Qux');
        },
        null,
        'Operation Qux'
    )
);

try {
    $transaction->commit();
} catch (FailedRollbackException $exception) {
    $formatter = new FailedRollbackFormatter();
    echo $formatter->format($exception) . PHP_EOL;
}